### ISSUE TITLE
It is not working at all

### ISSUE THREAD

**Issue by thetutlage** [jshttp/type-is#18]
I have no idea why it is not working , i am using vanilla http server and superagent to make the request. Here's how it looks

```javascript
    var server = http.createServer(function(req, res) {
      var type = is(req,["json"]);
      res.writeHead(200, {
        "Content-type": "text/plain"
      });
      res.end(type);
    });

    supertest(server)
      .get("/")
      .set("content-type", "application/json")
      .end(function(err, res) {
        if (err) done(err);
        expect(res.text).toBe(true);
        done();
      });
```

When i log `is(req,["json"])` it returns null

**Comment by dougwilson** [comment]
I see you're setting a `Content-Type` request header, but you'd not sending a body or sending a `Content-Length`. Your request would need to actually contain an entity (body) for your request to actually be able to be anything (i.e. the request is not json, since there is no entity to be json).

**Comment by dougwilson** [comment]
From the documentation https://github.com/jshttp/type-is#each-type-can-be :

> null will be returned if the request does not have a body.
