### ISSUE TITLE
Support for application/vnd.api+json

### ISSUE THREAD

**Issue by digitalsadhu** [jshttp/type-is#21]
This is the media type JSON API uses and should be treated as JSON. Am I correct in understanding that currently this media type is not directly supported?

**Comment by dougwilson** [comment]
> Am I correct in understanding that currently this media type is not directly supported?

That is not correct as far as I know. Can you explain how you came to this conclusion? Perhaps it's just a misunderstanding of the documentation in the README?

**Comment by digitalsadhu** [comment]
I'm sure I'm wrong, made the assumption when looking at body parser after finding that it doesn't support application/vnd.api+json. I figured it was likely the case that type-is simply wasn't reporting application/vnd.api+json as json.

**Comment by dougwilson** [comment]
The `body-parser` documentation of `type` (https://github.com/expressjs/body-parser#type) says that it is specifically sending this module the type `appliation/json`, which is a distinctly different type from `application/vnd.api+json`.

Even if you give this module the string `json`, this module will expand it to the type for that file extension (https://github.com/jshttp/type-is#each-type-can-be), so `.json` files are `application/json`.

**Comment by digitalsadhu** [comment]
Awesome, thanks for the explanation. That clears things up nicely for me.
