### ISSUE TITLE
Invalid for 'application/vnd.api+json

### ISSUE THREAD

**Issue by yordis** [jshttp/type-is#25]
I am using this configuration in express
```js
app.use(bodyParser.json({ type: 'application/vnd.api+json' }))
```
and I am sending this header `Content-Type: application/vnd.api+json`

I am getting `invalid json`

**Comment by yordis** [comment]
I so sorry for open this. Basically this was a legit Postman issue like 1K more. Sorry.

**Comment by dougwilson** [comment]
Hi @yordis , it's OK :) You probably also meant to file this issue against the `body-parser` module, as this library just does string matching, while the `invalid json` is actually from parsing the body itself, a part of `body-parser`.

**Comment by yordis** [comment]
@dougwilson yeah but I tracked down and was a matching problem. Even I am still without understand what Postman did there so I just use a tool that actually help me out.

Thanks a lot!

**Comment by dougwilson** [comment]
Ah, gotcha. I guess you had to problems: a matching problem here and a different `invalid json` issue. I only mentioned `body-parser`, because they way this module works in `body-parser`, any issue here would not trigger an `invalid json` message. Sorry for the confusion!

**Comment by yordis** [comment]
@dougwilson now reading my comment, very poor comment, :smile: next time I should explain better.
