### ISSUE TITLE
node example.js fails on Error

### ISSUE THREAD

**Issue by mncourt** [jshttp/type-is#29]
Error function fail in node

C:\Temp\generate-schema\node_modules\type-of-is>node --version
v6.9.4

C:\Temp\generate-schema\node_modules\type-of-is>node example.js
[Function: String]
[Function: Number]
[Function: Object]
[Function: Array]
null
undefined
[Function: Boolean]
[Function: Function]
[Function: RegExp]
[Function: Date]
**{ [Function: Error]
  captureStackTrace: [Function: captureStackTrace],
  stackTraceLimit: 10 }**
String
Number
Object
Array
null
undefined
Boolean
Function
RegExp
Date
Error
true
false
true
true
false
false
true
true
true
false
true
false
[Function: Person]
true
false
true
true
[Function: Object]
[Function: Number]
[Function: Number]
[Function: Number]
[Function: Object]
[Function: Object]
T
true
false

**Comment by dougwilson** [comment]
There is no file example.js in this module, so not sure what you are seeing.

**Comment by dougwilson** [comment]
Oh, your path says module is "type-of-is" but this is a different module. You probably reported this issue to the wrong place.

**Comment by mncourt** [comment]
Ahh thx.
