### ISSUE TITLE
+ suffix and wildcard

### ISSUE THREAD

**Issue by lbaldini** [jshttp/type-is#33]
Hi, I'm trying to use the *+json suffix but I can't make it work.

```
var typeis = require('type-is')

var mediaType = 'application/json'
typeis.is(mediaType, ['application/*'])       // 'application/json'
typeis.is(mediaType, ['application/json'])    // 'application/json'
typeis.is(mediaType, ['application/*+json'])  // false
```

In the main documentation is written 
> A suffix such as +json. This can be combined with a wildcard such as */vnd+json or application/*+json. The full mime type will be returned if matched.
> 

How the *+ suffix works? I've tryied to look at the code but I found something strange (line 215):
```
  // validate suffix wildcard
  if (expectedParts[1].substr(0, 2) === '*+') {
    return expectedParts[1].length <= actualParts[1].length + 1 &&
      expectedParts[1].substr(1) === actualParts[1].substr(1 - expectedParts[1].length)
  }
```
Here:
   expectedParts[1] = "*+json" 
   actualParts[1] = "json"

Now, expectedParts[1] starts with "\*+" but then the first part of the return expression is false:
  expectedParts[1].length is > than actualParts[1].length+1  ... should't be +2 instead (* and +)?

But even if I use +2 the second part seems wrong as well... 
   expectedParts[1].substr(**2**) not expectedParts[1].substr(1)... 

What am I missing?

**Comment by dougwilson** [comment]
The type you are checking against "application/json" does not have a suffix, so doesn't match. "application/json+json" would match since the type has the +json suffix.
