### ISSUE TITLE
TypeError: argument string is required - error when content type is missing

### ISSUE THREAD

**Issue by Darker** [jshttp/type-is#35]
This library is used by body parser in Express. If there is no "content-type" header, the library throws error at this line:
```
function parse(string) {
  if (!string) {
    throw new TypeError('argument string is required')
  }

  // support req/res-like objects as argument
  if (typeof string === 'object') {
    string = getcontenttype(string)
  }
```

This happens because you don't check if the header existed in the first place:

```
function typeofrequest (req, types_) {
  var types = types_

  // no body
  if (!hasbody(req)) {
    return null
  }

  // support flattened arguments
  if (arguments.length > 2) {
    types = new Array(arguments.length - 1)
    for (var i = 0; i < types.length; i++) {
      types[i] = arguments[i + 1]
    }
  }

  // request content type
// BAD BAD BAD!!!
  var value = req.headers['content-type']

  return typeis(value, types)
}
```
In the above code you send `undefined` to the `typeis` function.

Full stack trace:
```
 	parse [index.js] Line 141	JavaScript
 	normalizeType [index.js] Line 239	JavaScript
 	tryNormalizeType [index.js] Line 258	JavaScript
 	typeis [index.js] Line 48	JavaScript
>	typeofrequest [index.js] Line 142	JavaScript
```

**Comment by dougwilson** [comment]
Thanks for the report! Would you be interested in submitting a pull request with a fix here? Or provide the code and steps to reproduce and I can debug through it and produce a test case and fix 👍

**Comment by dougwilson** [comment]
Just based on your stack trace, you should not be getting any error, because it's caught right here: https://github.com/jshttp/type-is/blob/master/index.js#L259

**Comment by dougwilson** [comment]
Closing due to no response.
