### ISSUE TITLE
Extend support for media-typer 1.0.1

### ISSUE THREAD

**Issue by utkarsh2102** [jshttp/type-is#39]
https://github.com/jshttp/type-is/blob/dc723b95e2c52c689cf9d4cefbc5d91e74f7524a/package.json#L12

Since media-typer 1.0.1 is available, can the support for the same be extended?
Because this breaks with the newer version of media-typer.

**Comment by dougwilson** [comment]
I'm not sure what the question is? This module cannot use the 1.x series of media-typer because this module uses the features of the old 0.x series. The package.json is correct right now, that this module requires 0.3.0. There is no direct path to upgrade to the 1.x series, and the 0.x series is still supported for any bug fixes etc.

**Comment by utkarsh2102** [comment]
@dougwilson, so the type-is would break if media-typer 1.0.1 is installed, no?
Could something be done for the same?
When could we expect the upgrade for type-is so that it works fine with 1.x series?

**Comment by dougwilson** [comment]
No, if you install media-typer 1 it won't break this module. Npm will install a second copy of media-typer 0.3.0 just for this module's use, so it doesn't affect what version you can use.

**Comment by utkarsh2102** [comment]
@dougwilson, I am not using `npm`.
I am updating the module `media-typer` in the Debian repositories.
And due to that, `type-is` would break :(

**Comment by dougwilson** [comment]
There is no way to make this module work with media-typer 1.x. whatever package manager you use needs to honor our dependency versions declared in package.json

**Comment by utkarsh2102** [comment]
Ah, okay :(

**Comment by dougwilson** [comment]
Alright, made some upstream changes and just landed a commit that will upgrade the `media-typer` to the 1.x series.
