### ISSUE TITLE
Content type with profile not matching as expected

### ISSUE THREAD

**Issue by wmurphyrd** [jshttp/type-is#44]
Version 1.6.18

`typeIs.is('application/ld+json; profile="https://www.w3.org/ns/activitystreams"', ['application/ld+json; profile="https://www.w3.org/ns/activitystreams"'])`

Evaluates to `false`. It seems to use different normalization methods for value and type

**Comment by dougwilson** [comment]
This is because what you provided as the `types` argument is not valid. You can find the list of allowed strings in that array in the documentation here: https://github.com/jshttp/type-is#typeisrequest-types

**Comment by dougwilson** [comment]
There is an open issue #14 to support parameters in the `types` argument, which I think is what you're asking to support.

**Comment by wmurphyrd** [comment]
Ah thanks. I'm just trying to implement [this W3 spec](https://www.w3.org/TR/activitypub/#retrieving-objects). I'm sure It will work fine without specifying the profile in my types list

**Comment by dougwilson** [comment]
Gotcha, makes sense. So yes, this library doesn't let you match on the parameters. The only way you can do it currently is to include the `content-type` library to get the library:

``` js
var contentType = require('content-type')
var typeis = require('type-is')

// ... later on

if (typeis(req, 'application/ld+json') && contentType.parse(req).parameters.profile === 'https://www.w3.org/ns/activitystreams') {
  // accepts that specific thing
}
```
